# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SYAShortVideoWithSocial' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
pod 'PLShortVideoKit', '~> 1.6.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.10'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'IQKeyboardManager', '~> 5.0.0'
pod 'Masonry', '~> 1.1.0'
pod 'ReactiveCocoa', '~> 2.5’
pod 'CYLTabBarController', '~> 1.13.1'
  # Pods for SYAShortVideoWithSocial

end
