# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SYAShortVideoWithSocial' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!
pod 'PLShortVideoKit', '~> 1.5.0'
  # Pods for SYAShortVideoWithSocial

end
